### ISSUE TITLE
Problem calling rds_offer.reserved_upfront()

### ISSUE THREAD

**Issue by mateusrangel** [lyft/awspricing#25]
rds_offer.reserved_upfront(
  'db.t2.large',
  'MySQL',
  license_model='No license required',
  deployment_option='Multi-AZ',
  region='us-east-1',
  lease_contract_length='1yr',
  pucharse_option ='All Upfront',
)

TypeError: reserved_upfront() got an unexpected keyword argument 'pucharse_option'

**Comment by InternetExplorer7** [comment]
Is this because purchase_option is misspelled?

**Comment by mateusrangel** [comment]
thanks haha
