### ISSUE TITLE
Cannot Find SKU for EC2s

### ISSUE THREAD

**Issue by Latsyrc9** [lyft/awspricing#28]
(venv) Latsyrc$ pip install awspricing
Requirement already satisfied: awspricing in ./venv/lib/python3.7/site-packages (1.1.4)
Requirement already satisfied: requests<3.0.0,>=2.5.0 in ./venv/lib/python3.7/site-packages (from awspricing) (2.19.1)
Requirement already satisfied: six<2.0.0,>=1.0.0 in ./venv/lib/python3.7/site-packages (from awspricing) (1.11.0)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in ./venv/lib/python3.7/site-packages (from requests<3.0.0,>=2.5.0->awspricing) (1.23)
Requirement already satisfied: idna<2.8,>=2.5 in ./venv/lib/python3.7/site-packages (from requests<3.0.0,>=2.5.0->awspricing) (2.7)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.7/site-packages (from requests<3.0.0,>=2.5.0->awspricing) (2018.10.15)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./venv/lib/python3.7/site-packages (from requests<3.0.0,>=2.5.0->awspricing) (3.0.4)
(venv) Latsyrc$ python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 20:42:06)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import awspricing
>>> ec2_offer = awspricing.offer('AmazonEC2')
>>> ec2_offer.ondemand_hourly(
...     'cc2.8xlarge',
...     region='us-east-1',
...     operating_system='Linux'
... )
2.0
>>> ec2_offer.ondemand_hourly(
...     'm1.small',
...     region='us-east-1',
...     operating_system='Linux'
... )
0.044
>>> ec2_offer.ondemand_hourly(
...     't2.small',
...     region='us-east-1',
...     operating_system='Linux'
... )
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/Users/Latsyrc/venv/lib/python3.7/site-packages/awspricing/offers.py", line 208, in ondemand_hourly
    region=region
  File "/Users/Latsyrc/venv/lib/python3.7/site-packages/awspricing/offers.py", line 190, in get_sku
    .format(attributes))
ValueError: Unable to lookup SKU for attributes: ['t2.small', 'Linux', 'Shared', 'No License required', 'NA', 'US East (N. Virginia)']

**Comment by Jayliu95** [comment]
There might be an issue with the latest version of AWS pricing. Use an older version 
 like awspricing.offer('AmazonEC2', version="20181011211712")
