### ISSUE TITLE
Add RDS offers

### ISSUE THREAD

**Issue by bclodius** [lyft/awspricing#7]
@garrettheel I've found this module really helpful and would like to contribute back by adding RDS offers.  It will likely take me some time but wanted to check if your open to a contribution for RDS?

**Comment by garrettheel** [comment]
@bclodius that's great to hear! An RDS contribution would be great, I look forward to seeing what you come up with :)

I added https://github.com/lyft/awspricing/blob/master/CONTRIBUTING.md with a note about our CLA if you want to take a quick look at that.

**Comment by bclodius** [comment]
@garrettheel took an initial stab; let me know what you think.  I'm facing a "401" issue when trying to sign the CLA.

![image](https://cloud.githubusercontent.com/assets/590724/26285546/1a4b2e7a-3e20-11e7-8cba-41aa6111c7ea.png)
